clean:
	rm *.bin
	rm *.png

test1:
	python GenRandom.py ../Test/Random.bin
	python BinToImg.py ../Test/Random.bin

test2:
	python BinToImg.py BinToImg.py	

test3:
	python BinToImg.py ../Test/Test.pdf	
